# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x0corchestrator\"$\n\x0fRegisterRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"_\n\x10RegisterResponse\x12\x15\n\rassigned_rank\x18\x01 \x01(\x05\x12\x12\n\nworld_size\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\"8\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\")\n\x11HeartbeatResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\xab\x01\n\x0cOrchestrator\x12I\n\x08Register\x12\x1d.orchestrator.RegisterRequest\x1a\x1e.orchestrator.RegisterResponse\x12P\n\rSendHeartbeat\x12\x1e.orchestrator.HeartbeatRequest\x1a\x1f.orchestrator.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=36
  _globals['_REGISTERREQUEST']._serialized_end=72
  _globals['_REGISTERRESPONSE']._serialized_start=74
  _globals['_REGISTERRESPONSE']._serialized_end=169
  _globals['_HEARTBEATREQUEST']._serialized_start=171
  _globals['_HEARTBEATREQUEST']._serialized_end=227
  _globals['_HEARTBEATRESPONSE']._serialized_start=229
  _globals['_HEARTBEATRESPONSE']._serialized_end=270
  _globals['_ORCHESTRATOR']._serialized_start=273
  _globals['_ORCHESTRATOR']._serialized_end=444
# @@protoc_insertion_point(module_scope)
